# spring.datasource.url= jdbc:postgresql://localhost:5432/visitor_api
# spring.datasource.username=postgres
# spring.datasource.password=jaqueta
# spring.datasource.driver-class-name=org.postgresql.Driver
# spring.jpa.hibernate.ddl-auto=update

spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/visitor_api
        username: postgres
        password: jaqueta
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update